language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

sudo: false

before_script:
    - composer self-update
    - composer install

notifications:
  email: philipp.braeutigam@googlemail.com