language: php

php:
  - 5.3
  - 5.4
  - 5.5

sudo: false

before_script:
    - composer self-update
    - composer install

script:
    - vendor/bin/phpunit --coverage-clover coverage.clover --stderr --verbose

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
  email: philipp.braeutigam@googlemail.com